### PR TITLE
Check for css2 style

### PR DESCRIPTION
**Pull request by radeno**

### CODE REVIEW

**Comment by joncasey** [comment]
Looks pretty cool, @radeno.
Is this is a consistent thing for newer font families?
I'm not familiar with it.

**Comment by joncasey** [comment]
Ahh, found some documentation on it. It's the api for Variable Fonts.
https://developers.google.com/fonts/docs/css2
https://fonts.google.com/variablefonts

**Comment by joncasey** [comment]
Closed in v0.4.0 with slightly different approach.

**Comment by radeno** [comment]
Nice solution. 👍  my solution was for my requirements. Yours is cleaner. Thank you.

**Pull request closed without merging**
